### ISSUE TITLE
Suddenly getting this error on loginpass.

### ISSUE THREAD

**Issue by sn10** [authlib/loginpass#47]
```
Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
web_1       |     return self.wsgi_app(environ, start_response)
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
web_1       |     response = self.handle_exception(e)
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
web_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
web_1       |     reraise(exc_type, exc_value, tb)
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
web_1       |     raise value
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
web_1       |     response = self.full_dispatch_request()
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
web_1       |     rv = self.handle_user_exception(e)
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
web_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
web_1       |     reraise(exc_type, exc_value, tb)
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
web_1       |     raise value
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
web_1       |     rv = self.dispatch_request()
web_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
web_1       |     return self.view_functions[rule.endpoint](**req.view_args)
web_1       |   File "/usr/local/lib/python3.6/site-packages/loginpass/_flask.py", line 47, in auth
web_1       |     token = remote.authorize_access_token()
web_1       |   File "/usr/local/lib/python3.6/site-packages/authlib/flask/client/oauth.py", line 261, in authorize_access_token
web_1       |     token = self.fetch_access_token(redirect_uri, request_token, **params)
web_1       |   File "/usr/local/lib/python3.6/site-packages/authlib/client/oauth_client.py", line 174, in fetch_access_token
web_1       |     token = session.fetch_access_token(token_endpoint, **kwargs)
web_1       |   File "/usr/local/lib/python3.6/site-packages/authlib/client/oauth2_session.py", line 97, in fetch_access_token
web_1       |     return self.fetch_token(url, **kwargs)
web_1       |   File "/usr/local/lib/python3.6/site-packages/authlib/oauth2/client.py", line 167, in fetch_token
web_1       |     headers=headers, **session_kwargs
web_1       |   File "/usr/local/lib/python3.6/site-packages/authlib/oauth2/client.py", line 184, in _fetch_token
web_1       |     return self.parse_response_token(resp.json())
web_1       |   File "/usr/local/lib/python3.6/site-packages/authlib/oauth2/client.py", line 305, in parse_response_token
web_1       |     self.handle_error(error, description)
web_1       |   File "/usr/local/lib/python3.6/site-packages/authlib/client/oauth2_session.py", line 109, in handle_error
web_1       |     raise OAuthError(error_type, error_description)
web_1       | authlib.common.errors.AuthlibBaseError: invalid_request: Missing parameter: redirect_uri

```

So as I said everything was working and suddenly now I get this error, I am honestly not sure what could be wrong.

**Comment by aogier** [comment]
Hi, I can confirm an identical error on a starlette's client setup:

```python
config = Config(".env")  # pylint: disable=invalid-name
oauth = OAuth(config)

CONF_URL = 'https://accounts.google.com/.well-known/openid-configuration'
oauth.register(
    name='google',
    server_metadata_url=CONF_URL,
    client_kwargs={
        'scope': 'openid email profile'
    }
)

async def login(request):
    redirect_uri = request.url_for('auth')
    return await oauth.google.authorize_redirect(request, redirect_uri)


async def auth(request):
    logging.critical(request.headers)
    token = await oauth.google.authorize_access_token(request)
    user = await oauth.google.parse_id_token(request, token)
    request.session['user'] = dict(user)
    return RedirectResponse(url='/')
```

when `/auth` endpoint is hit, I get this traceback (first line is mine):

```
[osso] CRITICAL: Headers({'host': '[REDACTED]', 'x-request-id': '299db1f2a6d8f187459083ed590d4adb', 'x-real-ip': '10.42.0.1', 'x-forwarded-for': '10.42.0.1', 'x-forwarded-host': '[REDACTED]', 'x-forwarded-port': '443', 'x-forwarded-proto': 'https', 'x-scheme': 'https', 'user-agent': '[REDACTED]', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'accept-language': 'en-US,en;q=0.5', 'accept-encoding': 'gzip, deflate, br', 'referer': 'https://accounts.google.com/', 'dnt': '1', 'upgrade-insecure-requests': '1'})
[osso] INFO:     10.42.0.1:0 - "GET /auth?state=VNyCSjjCXSojWBTqNjsm3XlxBSJEgg&code=4%2FwwEnVamW5jzr4hOz4agsa1kjrKBlCOrMJTdO0pbFM9nq9qDbJ7-riJQ4Sh9TeokDyvz47FnRtY4DQsMMNH3N_II&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=consent HTTP/1.1" 500 Internal Server Error
[osso] ERROR:    Exception in ASGI application
[osso] Traceback (most recent call last):
[osso]   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
[osso]     result = await app(self.scope, self.receive, self.send)
[osso]   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
[osso]     return await self.app(scope, receive, send)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
[osso]     await self.middleware_stack(scope, receive, send)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
[osso]     raise exc from None
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
[osso]     await self.app(scope, receive, _send)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette_authlib/middleware.py", line 122, in __call__
[osso]     await self.app(scope, receive, send_wrapper)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
[osso]     raise exc from None
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
[osso]     await self.app(scope, receive, sender)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
[osso]     await route.handle(scope, receive, send)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
[osso]     await self.app(scope, receive, send)
[osso]   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
[osso]     response = await func(request)
[osso]   File "./osso/app.py", line 79, in auth
[osso]     token = await oauth.google.authorize_access_token(request)
[osso]   File "/usr/local/lib/python3.7/site-packages/authlib/integrations/starlette_client/integration.py", line 58, in authorize_access_token
[osso]     return await self.fetch_access_token(**params)
[osso]   File "/usr/local/lib/python3.7/site-packages/authlib/integrations/base_client/async_app.py", line 105, in fetch_access_token
[osso]     token = await client.fetch_token(token_endpoint, **kwargs)
[osso]   File "/usr/local/lib/python3.7/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 120, in _fetch_token
[osso]     return self.parse_response_token(resp.json())
[osso]   File "/usr/local/lib/python3.7/site-packages/authlib/oauth2/client.py", line 348, in parse_response_token
[osso]     self.handle_error(error, description)
[osso]   File "/usr/local/lib/python3.7/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 76, in handle_error
[osso]     raise OAuthError(error_type, error_description)
[osso] authlib.common.errors.AuthlibBaseError: invalid_request: Missing parameter: redirect_uri

```

**Comment by aogier** [comment]
@sn10 FYI I've found that `Missing parameter: redirect_uri` is a response google give back to us, you can read more here https://github.com/lepture/authlib/issues/196 ... I'm trying to dig further on that issue did you had some luck in the meanwhile?  
Ciao!

**Comment by aogier** [comment]
I've found I was setting a wrong session cookie max-age and that was the problem, maybe even yours? ciao

**Comment by lepture** [comment]
Usually this is caused by your wrong settings on `secret_key`.
